spring.application.name=REWARDSERVICE
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/revastra_reward_db
spring.datasource.username=postgres
spring.datasource.password=Azure@345221
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

logging.level.com.gl.rewardservice=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
